name: CI

on: [push, pull_request]

jobs:
    unix-test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest, macos-latest]

        steps:
            - name: Update dependencies on macOS
              if: runner.os == 'macOS'
              run: |
                cd "$(brew --repository)/Library/Taps/hombrew"
                ls
                # ls
                # cd hombrew-core/Formular
                # ls

            - uses: actions/checkout@v2

            - name: rust setup
              id: rust-setup
              run: |
                  rustup install $(cat rust-toolchain)
                  rustup component add rustfmt-preview
                  echo "::set-output name=date::$(/bin/date)"

            - name: rust cache
              uses: actions/cache@v2
              with:
                  path: |
                    ~/.cargo/registry/cache
                    ~/.cargo/git
                    ./rust_src/target
                  key: ${{ runner.os }}-build-${{ hashFiles('**/rust-toolchain', '**/Cargo.toml*', '**/rustfmt.toml') }}-test6

            - name: build cache
              uses: hendrikmuhs/ccache-action@v1
              with:
                  key: ${{ runner.os }}-build-ccache

            - name: Install dependencies on Linux
              if: runner.os == 'Linux'
              run: |
                  sudo apt install -y texinfo libx11-dev libxpm-dev libjpeg-dev libpng-dev libgif-dev libtiff-dev libgtk2.0-dev libncurses-dev automake autoconf libgnutls28-dev zlib1g-dev libgccjit-9-dev clang llvm lld make
                  # build-essential

                  export LD="lld"
                  export AR="llvm-ar"
                  export AS="llvm-as"
                  export RANLIB="llvm-ranlib"
                  export CCFLAGS=" -fuse-ld=lld"
                  export CXXFLAGS=" -fuse-ld=lld"
                  export RUSTFLAGS=" -Clink-arg=-fuse-ld=lld"

            - name: zld cache(for mac)
              if: runner.os == 'macOS'
              uses: actions/cache@v2
              with:
                  path: /tmp/zld-*
                  key: ${{ runner.OS }}-build-zld-${{ steps.rust-setup.outputs.date }}
                  restore-keys: |
                      ${{ runner.OS }}-build-zld-${{ steps.rust-setup.outputs.date }}
                      ${{ runner.OS }}-build-zld-

            - name: Install dependencies on macOS
              if: runner.os == 'macOS'
              run: |
                  env HOMEBREW_NO_AUTO_UPDATE=1
                  brew install gnutls texinfo automake autoconf llvm michaeleisel/zld/zld
                  # llvm --with-clang --with-lld
                  # libx11 libxpm jpeg libpng giflib libtiff gtk+3 ncurses

                  # https://github.com/memkind/memkind/issues/33
                  alias nproc="sysctl -n hw.logicalcpu"

                  which zld
                  # https://afnan.io/posts/2018-10-01-using-the-latest-llvm-release-on-macos/
                  # https://steipete.com/posts/zld-a-faster-linker/
                  export PATH="/usr/local/opt/llvm/bin:$PATH"
                  export CPLUS_INCLUDE_PATH=$(llvm-config --includedir):$CPLUS_INCLUDE_PATH
                  export LD_LIBRARY_PATH=$(llvm-config --libdir):$LD_LIBRARY_PATH
                  export LD="/usr/local/bin/zld"
                  export AR="/usr/local/opt/llvm/bin/llvm-ar"
                  export AS="/usr/local/opt/llvm/bin/llvm-as"
                  export RANLIB="/usr/local/opt/llvm/bin/llvm-ranlib"
                  export CCFLAGS=" -fuse-ld=/usr/local/bin/zld"
                  export CXXFLAGS=" -fuse-ld=/usr/local/local/bin/zld"
                  export RUSTFLAGS=" -Clink-arg=-fuse-ld=/usr/local/bin/zld"
                  OTHER_LDFLAGS=" -fuse-ld=/usr/local/bin/zld"

            - name: rustfmt
              run: |
                  # Configure $PATH: Executables are installed to $HOME/bin
                  export PATH="$HOME/bin:$PATH"

                  ./autogen.sh && ./configure --without-makeinfo --with-x=no --with-ns=no --without-gconf --without-gsettings --without-native-compilation
                  admin/format-rust.sh

            - name: build
              run: |
                  export CARGO_INCREMENTAL=0
                  export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"

                  # which clang
                  # which clang++
                  # which lld
                  ./autogen.sh
                  # echo "CC: $CC"
                  # echo "LD: $LD"

                  # Compile with clang
                  echo "Compile with clang"
                  export CC="clang"
                  export CXX="clang++"
                  export CPP="clang -E"
                  # echo "CC: $CC"
                  # echo "LD: $LD"

                  # Debug Flags
                  # echo "Debug Process"
                  export RUSTFLAGS="-Zshare-generics=y -Copt-level=2 -Cdebuginfo=1 $RUSTFLAGS"
                  # -Dwarnings
                  # export WERROR_CFLAGS="-Werror -Wno-error=deprecated-declarations"
                  export CFLAGS="-O2 -g"
                  export CXXFLAGS="-O2 -g"

                  echo "Configure Process"
                  ./configure --enable-checking=glyphs --enable-rust-debug
                  # --enable-autodepend
                  # echo "CC: $CC"
                  # echo "LD: $LD"
                  echo "nproc: $((`nproc`+1))"
                  make -j$((`nproc`+1)) src

                  ## Reduce Cache
                  # Note that all of the above need to be repeated for `release/` instead of
                  # `debug/` if your build script builds artifacts in release mode.
                  # https://bheisler.github.io/post/efficient-use-of-travis-ci-cache-for-rust/
                  # Delete loose files in the debug directory
                  find ./rust_src/target/debug -maxdepth 1 -type f -delete
                  # Delete just meta data
                  rm -f  ./rust_src/target/.rustc_info.json

            - name: js fmt
              run: |
                  cd test/js/
                  ../../src/emacs --batch --eval '(deno "fmt" "--check")'
                  cd ../../rust_src/src
                  ../../src/emacs --batch --eval '(deno "fmt" "--check")'
                  cd ../../

            - name: run js tests
              run: |
                  cd test/js/
                  ../../src/emacs --batch --eval '(deno "test" "main.js" "--allow-read" "--allow-write")'
