name: CI

on: [push, pull_request]

jobs:
    unix-test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]

        steps:
            - uses: actions/checkout@v2


            - uses: pCYSl5EDgo/cat@master
              id: toolchain
              with:
                  path: rust-toolchain

            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ steps.toolchain.outputs.text }}
                  override: true
                  components: rustfmt-preview

            - uses: Swatinem/rust-cache@v1
              with:
                  key: ${{ runner.os }}-build-${{ hashFiles('**/rust-toolchain', '**/Cargo.toml*', '**/rustfmt.toml') }}
                  restore-keys: |
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-build

            - name: Install dependencies on Linux
              if: runner.os == 'Linux'
              run: |
                  sudo apt install -y build-essential texinfo libx11-dev libxpm-dev libjpeg-dev libpng-dev libgif-dev libtiff-dev libgtk2.0-dev libncurses-dev automake autoconf libgnutls28-dev zlib1g-dev libgccjit-9-dev

            - name: Install dependencies on macOS
              if: runner.os == 'macOS'
              run: |
                  brew install gnutls texinfo automake autoconf
                  # libx11 libxpm jpeg libpng giflib libtiff gtk+3 ncurses

                  # https://github.com/memkind/memkind/issues/33
                  alias nproc="sysctl -n hw.logicalcpu"

            - name: rustfmt
              run: |
                  # Configure $PATH: Executables are installed to $HOME/bin
                  export PATH="$HOME/bin:$PATH"

                  ./autogen.sh && ./configure --without-makeinfo --with-x=no --with-ns=no --without-gconf --without-gsettings --without-native-compilation
                  admin/format-rust.sh

            - name: build
              run: |
                  ./autogen.sh && RUSTFLAGS="-Dwarnings" WERROR_CFLAGS='-Werror -Wno-error=deprecated-declarations'
                  ./configure --enable-checking=glyphs
                  make -j$(nproc)

            - name: js fmt
              run: |
                  cd test/js/
                  ../../src/emacs --batch --eval '(deno "fmt" "--check")'
                  cd ../../rust_src/src
                  ../../src/emacs --batch --eval '(deno "fmt" "--check")'
                  cd ../../

            - name: run js tests
              run: |
                  cd test/js/
                  ../../src/emacs --batch --eval '(deno "test" "main.js" "--allow-read" "--allow-write")'
