name: CI

on: [push, pull_request]

jobs:
    unix-test:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: prepare rustfmt(linux)
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                  # Configure $PATH: Executables are installed to $HOME/bin
                  export PATH="$HOME/bin:$PATH"

                  sudo apt install -y libgnutls28-dev

            - name: prepare rustfmt(mac)
              if: ${{ matrix.os == 'macos-latest' }}
              run: |
                  # Configure $PATH: Executables are installed to $HOME/bin
                  export PATH="$HOME/bin:$PATH"

                  brew install gnutls

            - name: rustfmt
              run: |
                  rustup install $(cat rust-toolchain)
                  rustup component add rustfmt-preview
                  ./autogen.sh && ./configure --without-makeinfo --with-x=no --with-ns=no --without-gconf --without-gsettings
                  admin/format-rust.sh

            - name: prepare build(linux)
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                  sudo apt install -y build-essential texinfo libx11-dev libxpm-dev libjpeg-dev libpng-dev libgif-dev libtiff-dev libgtk2.0-dev libncurses-dev automake autoconf

            - name: prepare build(mac)
              if: ${{ matrix.os == 'macos-latest' }}
              run: |
                  # xcode-select --install ## Alreay Installed
                  brew install texinfo libx11 libxpm jpeg libpng giflib libtiff gtk+3 ncurses automake autoconf

                  # https://github.com/memkind/memkind/issues/33
                  alias nproc="sysctl -n hw.logicalcpu"

            - name: build
              run: |
                  ./autogen.sh && RUSTFLAGS="-Dwarnings" WERROR_CFLAGS='-Werror -Wno-error=deprecated-declarations'
                  ./configure --enable-checking=glyphs
                  make -j$(nproc)

            - name: js fmt
              run: |
                  cd test/js/
                  ../../src/emacs --batch --eval '(deno "fmt" "--check")'
                  cd ../../rust_src/src
                  ../../src/emacs --batch --eval '(deno "fmt" "--check")'
                  cd ../../

            - name: run js tests
              run: |
                  cd test/js/
                  ../../src/emacs --batch --eval '(deno "test" "main.js" "--allow-read" "--allow-write")'
